### PR TITLE
Make separators touch in non-horizontal-only contexts

### PR DESCRIPTION
**Pull request by chriskirknielsen**
When the separator is set to vertical, they will connect, and when both vertical and horizontal separators are set, they will all connect.

### CODE REVIEW

**Comment by zachleat** [comment]
Ah, there might be something wrong with the border clipping that happens on the container? I see scrollbars

image

apparently no PR is quick 😅

**Comment by chriskirknielsen** [comment]
Oh shoot, good catch! I think it should be fixed now. But it might break in RTL contexts. 👀

**Comment by zachleat** [comment]
v4.0.2

**Comment by zachleat** [comment]
`direction: rtl` renders the borders fine—thank you!

**Comment by zachleat** [comment]
v4.0.2 has shipped

**Pull request merged**
